"""Frozen public contract of the auto-switch engine.

Everything that wires a provider into auto-switching — the per-provider
``*_accounts`` callers, the restart hook, the polling timer — codes against the
surface pinned here: the shape of :func:`polytool.autoswitch.run_autoswitch`,
the shape of the :class:`polytool.autoswitch.SwitchOutcome` it returns, and the
fixed vocabulary of ``SWITCH_REASONS``.

It deliberately touches nothing private: no internal helper, no mock of module
internals, no assumption about how the decision is reached. Only public names,
real callables and real return values — so it keeps holding while the engine's
insides move.

This file pins the *shape*; the behaviour behind it — the threshold boundary,
candidate selection, the notification rules and the "never raises" promise for
a failing switch or restart hook — is pinned in ``tests/test_autoswitch.py``,
which is just as load-bearing.

**Do not edit this file to make a change pass.** A failure here is a breaking
change to every caller; change the callers' contract on purpose, or fix the
engine. Run with: ``uv run pytest``.
"""

from __future__ import annotations

import inspect
import os
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from polytool import autoswitch as aw
from polytool.usage_format import UsageWindow

# ── the frozen surface ───────────────────────────────────────────────────────

ENGINE_PARAMETERS = ("provider", "profiles", "active", "probe", "switch", "restart")

OUTCOME_FIELDS = (
    "provider",
    "switched",
    "reason",
    "from_profile",
    "to_profile",
    "used_pct",
    "error",
    "restarted",
)

REASONS = {
    "disabled",
    "no_active",
    "unknown",
    "below_threshold",
    "no_candidate",
    "switched",
    "switch_failed",
}


class _Sandbox(unittest.TestCase):
    """Config in a throwaway dir, notifications off — no OS popups, no network."""

    def setUp(self) -> None:
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        env = mock.patch.dict(
            os.environ,
            {"POLYTOOL_CONFIG_JSON": str(Path(tmp.name) / "config.json")},
            clear=False,
        )
        env.start()
        self.addCleanup(env.stop)
        aw.save_config({"enabled": True, "notify": "none", "switch_when_used_pct": 90})


class EngineSignatureContract(_Sandbox):
    def test_the_engine_takes_exactly_these_parameters_in_this_order(self) -> None:
        # Given/When: the engine's public signature
        params = inspect.signature(aw.run_autoswitch).parameters
        # Then: names and order are fixed — callers may pass them positionally
        self.assertEqual(tuple(params), ENGINE_PARAMETERS)
        for name in ENGINE_PARAMETERS:
            self.assertIs(
                params[name].kind, inspect.Parameter.POSITIONAL_OR_KEYWORD, name
            )

    def test_only_the_restart_slot_is_optional(self) -> None:
        # Given/When: the engine's public signature
        params = inspect.signature(aw.run_autoswitch).parameters
        # Then: the restart hook is an opt-in slot, everything else is required
        self.assertIsNone(params["restart"].default)
        for name in ("provider", "profiles", "active", "probe", "switch"):
            self.assertIs(params[name].default, inspect.Parameter.empty, name)

    def test_the_engine_is_callable_with_positional_arguments_only(self) -> None:
        # Given: the five required arguments, in order
        # When: the engine is called positionally
        outcome = aw.run_autoswitch(
            "testprov", ["alpha"], None, _probe({}), _switch([])
        )
        # Then: it runs and returns an outcome
        self.assertIsInstance(outcome, aw.SwitchOutcome)


class SwitchOutcomeContract(_Sandbox):
    def _switched_outcome(self) -> aw.SwitchOutcome:
        return aw.run_autoswitch(
            "testprov",
            ["alpha", "beta"],
            "alpha",
            _probe({"alpha": 95, "beta": 10}),
            _switch([]),
            lambda: True,
        )

    def test_every_field_a_caller_may_read_is_present(self) -> None:
        # Given: a completed run
        outcome = self._switched_outcome()
        # When/Then: each pinned field is readable
        for field in OUTCOME_FIELDS:
            getattr(outcome, field)

    def test_the_outcome_is_read_only(self) -> None:
        # Given: a completed run
        outcome = self._switched_outcome()
        # When: a caller tries to doctor the record
        # Then: it is refused — outcomes are values, not scratch space
        with self.assertRaises(AttributeError):
            outcome.switched = False  # type: ignore[misc]

    def test_the_fields_carry_the_pinned_types(self) -> None:
        # Given: a run that switched
        outcome = self._switched_outcome()
        # Then: the payload is exactly what callers are told to expect
        self.assertEqual(outcome.provider, "testprov")
        self.assertIsInstance(outcome.switched, bool)
        self.assertIn(outcome.reason, REASONS)
        self.assertEqual(outcome.from_profile, "alpha")
        self.assertEqual(outcome.to_profile, "beta")
        self.assertIsInstance(outcome.used_pct, int)
        self.assertIsNone(outcome.error)
        self.assertIsInstance(outcome.restarted, bool)

    def test_the_reason_vocabulary_is_fixed(self) -> None:
        # Given/When/Then: callers may switch on these, and only these
        self.assertEqual(set(aw.SWITCH_REASONS), REASONS)

    def test_to_profile_is_set_exactly_when_a_switch_happened(self) -> None:
        # Given: a run that switches and a run that does not
        switched = self._switched_outcome()
        untouched = aw.run_autoswitch(
            "testprov",
            ["alpha", "beta"],
            "alpha",
            _probe({"alpha": 10, "beta": 10}),
            _switch([]),
        )
        # Then: to_profile names the live profile only when there is one
        self.assertTrue(switched.switched)
        self.assertEqual(switched.to_profile, "beta")
        self.assertFalse(untouched.switched)
        self.assertIsNone(untouched.to_profile)

    def test_restarted_is_none_when_no_restart_hook_was_given(self) -> None:
        # Given: a switching run with the restart slot left empty
        outcome = aw.run_autoswitch(
            "testprov",
            ["alpha", "beta"],
            "alpha",
            _probe({"alpha": 95, "beta": 10}),
            _switch([]),
        )
        # Then: "not asked for" is distinguishable from "tried and failed"
        self.assertTrue(outcome.switched)
        self.assertIsNone(outcome.restarted)


class EngineCycleContract(_Sandbox):
    """One caller, the public surface only, through the whole life cycle."""

    def test_a_caller_can_drive_the_full_cycle_with_the_public_surface(self) -> None:
        switches: list[str] = []
        restarts: list[str] = []

        def restart() -> bool:
            restarts.append("restart")
            return True

        # Given: plenty of quota left
        # When: the engine runs
        quiet = aw.run_autoswitch(
            "testprov",
            ["alpha", "beta"],
            "alpha",
            _probe({"alpha": 50, "beta": 10}),
            _switch(switches),
            restart,
        )
        # Then: nothing happens at all
        self.assertFalse(quiet.switched)
        self.assertEqual(quiet.reason, "below_threshold")
        self.assertEqual(switches, [])
        self.assertEqual(restarts, [])

        # Given: the active profile now over the threshold
        # When: the engine runs again
        moved = aw.run_autoswitch(
            "testprov",
            ["alpha", "beta"],
            "alpha",
            _probe({"alpha": 95, "beta": 10}),
            _switch(switches),
            restart,
        )
        # Then: it switched to the emptiest account and ran the restart hook
        self.assertTrue(moved.switched)
        self.assertEqual(moved.reason, "switched")
        self.assertEqual((moved.from_profile, moved.to_profile), ("alpha", "beta"))
        self.assertEqual(switches, ["beta"])
        self.assertEqual(restarts, ["restart"])

        # Given: later, every account is over the threshold
        # When: the engine runs twice on that dead end
        dead_end = [
            aw.run_autoswitch(
                "testprov",
                ["alpha", "beta"],
                "beta",
                _probe({"alpha": 99, "beta": 97}),
                _switch(switches),
                restart,
            )
            for _ in range(2)
        ]
        # Then: both polls report the dead end without switching or restarting
        for outcome in dead_end:
            self.assertFalse(outcome.switched)
            self.assertEqual(outcome.reason, "no_candidate")
            self.assertIsNone(outcome.to_profile)
        self.assertEqual(switches, ["beta"])
        self.assertEqual(restarts, ["restart"])

    def test_turning_the_feature_off_stops_the_engine_dead(self) -> None:
        # Given: auto-switching disabled through the public config API
        aw.save_config({"enabled": False})
        probed: list[str] = []
        switches: list[str] = []

        def probe(name: str) -> UsageWindow | None:
            probed.append(name)
            return UsageWindow(percentage=99, reset_time=None, window_minutes=None)

        # When: the engine runs on an exhausted profile
        outcome = aw.run_autoswitch(
            "testprov", ["alpha", "beta"], "alpha", probe, _switch(switches)
        )
        # Then: no usage lookups, no switch, and the reason says why
        self.assertFalse(outcome.switched)
        self.assertEqual(outcome.reason, "disabled")
        self.assertEqual(probed, [])
        self.assertEqual(switches, [])

    def test_a_probe_that_cannot_answer_never_breaks_a_caller(self) -> None:
        # Given: one candidate with no usage data and one that raises
        def probe(name: str) -> UsageWindow | None:
            if name == "alpha":
                return UsageWindow(percentage=95, reset_time=None, window_minutes=None)
            if name == "beta":
                return None
            raise RuntimeError("usage endpoint down")

        switches: list[str] = []
        # When: the engine runs
        outcome = aw.run_autoswitch(
            "testprov", ["alpha", "beta", "gamma"], "alpha", probe, _switch(switches)
        )
        # Then: it reports a dead end instead of switching blind or raising
        self.assertFalse(outcome.switched)
        self.assertEqual(outcome.reason, "no_candidate")
        self.assertEqual(switches, [])


def _probe(used: dict[str, int]):
    """A probe callable over a ``{profile: used_pct}`` table."""

    def probe(name: str) -> UsageWindow | None:
        if name not in used:
            return None
        return UsageWindow(
            percentage=used[name], reset_time=None, window_minutes=None
        )

    return probe


def _switch(recorder: list[str]):
    """A switch callable that records what it was asked to activate."""

    def switch(name: str) -> bool:
        recorder.append(name)
        return True

    return switch
